--GRUPO 
--Eduardo Bezerra - RM: 98890
--Jefferson Mendes de Farias Lima - RM: 552052
--Joao Vitor Vicente Benjamin - RM: 98938
--Luiz Felipe Biazzola Cavalcante - RM: 99250
--Silas Henrique da Silva Oliveira - RM: 98965

-----------------DROP DAS TABELAS UTILIZANDO DROP TABLE-------------------------
--------------------------------------------------------------------------------


--DROP DE TODAS AS TABELAS EM ORDEM DE EXCLUSAO
DROP TABLE T_JR_ATENDIMENTO;
DROP TABLE T_JR_LOCALIZACAO;
DROP TABLE T_JR_MODAL;
DROP TABLE T_JR_PRESTADOR;
DROP TABLE T_JR_VEICULO_CLIENTE;
DROP TABLE T_JR_SEGURO;
DROP TABLE T_JR_CLIENTE;
DROP TABLE T_JR_ENDERECO;
DROP TABLE T_JR_FABRICANTE;
DROP TABLE T_JR_IMPLEMENTO;


-----------------CRIACAO DAS TABELAS UTILIZANDO CREATE TABLE--------------------
--------------------------------------------------------------------------------


--CRIACAO DA TABELA T_JR_FABRICANTE
CREATE TABLE T_JR_FABRICANTE(
	id_fabricante NUMERIC CONSTRAINT PK_T_JR_FABRICANTE PRIMARY KEY,
	nome VARCHAR2(60) NOT NULL,
	modelo VARCHAR2(60) NOT NULL

);

--CRIACAO DA TABELA T_JR_IMPLEMENTO
CREATE TABLE T_JR_IMPLEMENTO(
	id_implemento NUMERIC CONSTRAINT PK_T_JR_IMPLEMENTO PRIMARY KEY,
	tipo_implemento VARCHAR2(60) NOT NULL
);

--CRIACAO DA TABELA T_JR_ENDERECO
CREATE TABLE T_JR_ENDERECO(
	id_endereco NUMERIC CONSTRAINT PK_T_JR_ENDERECO PRIMARY KEY,
	cep VARCHAR2(60) NOT NULL,
	logradouro VARCHAR2(60) NOT NULL,
	numero NUMERIC NOT NULL,
	complemento VARCHAR2(60),
	referencia VARCHAR2(60)
);

--CRIACAO DA TABELA T_JR_CLIENTE
CREATE TABLE T_JR_CLIENTE(
	id_cliente NUMERIC CONSTRAINT PK_T_JR_CLIENTE PRIMARY KEY,
	cpf VARCHAR2(60) NOT NULL UNIQUE,
	nome_completo VARCHAR2(60) NOT NULL,
	rg VARCHAR2(60) NOT NULL,
    id_endereco NUMERIC NOT NULL,
	CONSTRAINT FK_T_JR_CLIENTE_T_JR_ENDERECO FOREIGN KEY (id_endereco) REFERENCES T_JR_ENDERECO(id_endereco)

);

--CRIACAO DA TABELA T_JR_SEGURO
CREATE TABLE T_JR_SEGURO(
	numero_apolice VARCHAR2(60) CONSTRAINT PK_T_JR_SEGURO PRIMARY KEY,
    id_cliente NUMERIC NOT NULL,
    CONSTRAINT FK_T_JR_SEGURO_T_JR_CLIENTE FOREIGN KEY (id_cliente) REFERENCES T_JR_CLIENTE(id_cliente)
);

--CRIACAO DA TABELA T_JR_VEICULO_CLIENTE
CREATE TABLE T_JR_VEICULO_CLIENTE(
	id_veiculo NUMERIC CONSTRAINT PK_T_JR_VEICULO_CLIENTE PRIMARY KEY,
	placa VARCHAR2(60) NOT NULL,
	ano NUMERIC(4) NOT NULL,
	portas NUMERIC,
	renavam NUMERIC NOT NULL,
    numero_apolice VARCHAR2(60) NOT NULL,
    id_implemento NUMERIC NOT NULL,
    id_fabricante NUMERIC NOT NULL,
    id_cliente NUMERIC NOT NULL,
	CONSTRAINT FK_T_JR_VEICULO_CLIENTE_T_JR_SEGURO FOREIGN KEY (numero_apolice) REFERENCES T_JR_SEGURO(numero_apolice),
	CONSTRAINT FK_T_JR_VEICULO_CLIENTE_T_JR_IMPLEMENTO FOREIGN KEY (id_implemento) REFERENCES T_JR_IMPLEMENTO(id_implemento),
	CONSTRAINT FK_T_JR_VEICULO_CLIENTE_T_JR_FABRICANTE FOREIGN KEY (id_fabricante) REFERENCES T_JR_FABRICANTE(id_fabricante),
	CONSTRAINT FK_T_JR_VEICULO_CLIENTE_T_JR_CLIENTE FOREIGN KEY (id_cliente) REFERENCES T_JR_CLIENTE(id_cliente)
);

--CRIACAO DA TABELA T_JR_PRESTADOR
CREATE TABLE T_JR_PRESTADOR(
	id_prestador NUMERIC CONSTRAINT PK_T_JR_PRESTADOR PRIMARY KEY,
	cpf VARCHAR2(60) NOT NULL UNIQUE,
	nome_completo VARCHAR2(60) NOT NULL,
	rg VARCHAR2(60) NOT NULL,
    id_endereco NUMERIC NOT NULL,
	CONSTRAINT FK_T_JR_PRESTADOR_T_JR_ENDERECO FOREIGN KEY (id_endereco) REFERENCES T_JR_ENDERECO(id_endereco)
);

--CRIACAO DA TABELA T_JR_MODAL
CREATE TABLE T_JR_MODAL(
	id_modal numeric CONSTRAINT PK_T_JR_MODAL PRIMARY KEY,
	modelo VARCHAR2(60) NOT NULL,
	placa VARCHAR2(60) NOT NULL,
	disponibilidade NUMERIC(1) NOT NULL,
    id_prestador NUMERIC,
	CONSTRAINT FK_T_JR_MODAL_T_JR_PRESTADOR FOREIGN KEY (id_prestador) REFERENCES T_JR_PRESTADOR(id_prestador)
);

--CRIACAO DA TABELA T_JR_LOCALIZACAO
CREATE TABLE T_JR_LOCALIZACAO(
	id_localizacao NUMERIC CONSTRAINT PK_T_JR_LOCALIZACAO PRIMARY KEY,
	nome_rodovia VARCHAR2(60) NOT NULL,
	km NUMERIC(10) NOT NULL,
	cep VARCHAR2(60),
	referencia VARCHAR2(60)
);

--CRIACAO DA TABELA T_JR_ATENDIMENTO
CREATE TABLE T_JR_ATENDIMENTO(
	id_atendimento NUMERIC CONSTRAINT PK_T_JR_ATENDIMENTO PRIMARY KEY,
	data_atendimento DATE NOT NULL,
	pbtc NUMERIC NOT NULL,
    id_localizacao NUMERIC NOT NULL,
    id_cliente NUMERIC NOT NULL,
    id_veiculo NUMERIC NOT NULL,
    id_modal NUMERIC NOT NULL,
	CONSTRAINT FK_T_JR_ATENTIMENTO_T_JR_LOCALIZACAO FOREIGN KEY (id_localizacao) REFERENCES T_JR_LOCALIZACAO(id_localizacao),
	CONSTRAINT FK_T_JR_ATENTIMENTO_T_JR_CLIENTE FOREIGN KEY (id_cliente) REFERENCES T_JR_CLIENTE(id_cliente),
	CONSTRAINT FK_T_JR_ATENTIMENTO_T_JR_VEICULO_CLIENTE FOREIGN KEY (id_veiculo) REFERENCES T_JR_VEICULO_CLIENTE(id_veiculo),
	CONSTRAINT FK_T_JR_ATENTIMENTO_T_JR_MODAL FOREIGN KEY (id_modal) REFERENCES T_JR_MODAL(id_modal)

);